[colors]
ansi = [
    '#000000',
    '#e46d63',
    '#58c18f',
    '#e9e64d',
    '#77abd9',
    '#d38dd9',
    '#60c1de',
    '#eaeaea',
]
background = '#1d1d1d'
brights = [
    '#656565',
    '#e46d63',
    '#58c18f',
    '#e9e64d',
    '#77abd9',
    '#d38dd9',
    '#60c1de',
    '#eaeaea',
]
cursor_bg = '#d5d5d5'
cursor_fg = '#282828'
selection_fg = '#000000'
selection_bg = '#c3c2c3'
foreground = '#dcdcdc'